# Generated by Django 4.1.7 on 2023-04-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
