# Generated by Django 4.1.7 on 2023-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Date', models.CharField(blank=True, max_length=30, null=True)),
                ('Chair', models.IntegerField(blank=True, null=True)),
                ('Request', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
