# Generated by Django 4.1.7 on 2023-05-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='User',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
